### PR TITLE
chore(deps): use ratatui::crossterm instead of importing crossterm

### PR DESCRIPTION
**Pull request by joshka**
Alternative to: https://github.com/shuoli84/tui-menu/pull/15

### CODE REVIEW

**Comment by shuoli84** [comment]
I've added a new example in master, that one needs to do same change I guess..

**Comment by joshka** [comment]
> I've added a new example in master, that one needs to do same change I guess..

rebased on main and added

**Review by shuoli84 — APPROVED** [review]
LGTM

**Comment by shuoli84** [comment]
Thanks!

**Pull request merged**
