### PR TITLE
add a nested group example, this demos how to handle deeply nested me…

### LINKED ISSUE #4: Indent menu when first menu item is not rendered all the way on the left side.
I wanted to put an app title at the start of the line, but noticed that the menu renders at the left side of the window:

```rust
impl Widget for &mut App {
    fn render(self, area: Rect, buf: &mut Buffer) {
        use Constraint::*;
        let [top, main] = Layout::vertical([Length(1), Fill(1)]).areas(area);
        let [title, menu] = Layout::horizontal([Length(10), Fill(1)]).areas(top);

        Paragraph::new(self.content.as_str())
            .block(Block::bordered().title("Content").on_black())
            .render(main, buf);

        "tui-menu"
            .bold()
            .blue()
            .to_centered_line()
            .render(title, buf);

        // draw menu last, so it renders on top of other content
        Menu::new().render(menu, buf, &mut self.menu);
    }
}
```
Renders as:

demo

This is probably a super easy fix, but I wanted to check if @shuoli84 had any feedback before implementing it.
It would be a good idea to indent

### PR DESCRIPTION
**Pull request by shuoli84**
…nu structure.

Also align dropdown's x with menu bar

This should fixed the layout problem, also fixes #4

### CODE REVIEW

**Comment by micielski** [comment]
This kinda works, but it will conflict with my changes. This still crashes when the window menu is too small to render the menu, which I've already fixed (using Rect::clamp) and I will push it when I finish making the menu more responsive.

**Comment by joshka** [comment]
+1 to seeing a crash when making the window narrower than the first level width.

This also acts a bit weird when the nested items can't fit on the screen:
Level 3 fits
image
But level 4 doesn't:
image

I suspect that the size of the menus should probably automatically fit the contents too.

**Comment by shuoli84** [comment]
Level 4 is covering Level 3, so it appears weird, but the action should works as expected. Maybe add some visual indicator?
Dropdown width fits content doesn't solve the problem, it maybe better or worse depends on item's name length.

**Comment by joshka** [comment]
Just for reference, the way this is handled on my Mac's menu bar is that the menu that doesn't fit gets rendered the opposite direction. This seems like a good idea. E.g.:

image

**Comment by shuoli84** [comment]
Yes, it is a good idea. I'll do some quick experiments to test whether it feels right in tui

**Comment by shuoli84** [comment]
The tricky part is, if it automatically rendered on left side, then which key is step in, left or right.. Neither feels right..

**Comment by shuoli84** [comment]
How about stack it up? e.g
```bash
Nest1 > Nest2 > Nest3  |
.................Nest4|
.................Nest5|
```

**Comment by shuoli84** [comment]
@micielski @joshka take a look?

**Comment by joshka** [comment]
> The tricky part is, if it automatically rendered on left side, then which key is step in, left or right.. Neither feels right..

I'd say keep it consistent - right key always goes in even when it will render left.

**Comment by joshka** [comment]
> How about stack it up? e.g

This gets pretty confusing when you add more than one nested item:

<details><summary>Details</summary>
<p>

Add this:

```rust
vec![
                                        MenuItem::group(
                                            "Nested 4a",
                                            vec![
                                                MenuItem::group(
                                                    "Nested 5a",
                                                    vec![
                                                        MenuItem::group("Nested 6a", vec![]),
                                                        MenuItem::group("Nested 6b", vec![]),
                                                        MenuItem::group("Nested 6c", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5b",
                                                    vec![
                                                        MenuItem::group("Nested 6d", vec![]),
                                                        MenuItem::group("Nested 6e", vec![]),
                                                        MenuItem::group("Nested 6f", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5c",
                                                    vec![
                                                        MenuItem::group("Nested 6g", vec![]),
                                                        MenuItem::group("Nested 6h", vec![]),
                                                        MenuItem::group("Nested 6i", vec![]),
                                                    ],
                                                ),
                                            ],
                                        ),
                                        MenuItem::group(
                                            "Nested 4b",
                                            vec![
                                                MenuItem::group(
                                                    "Nested 5d",
                                                    vec![
                                                        MenuItem::group("Nested 6j", vec![]),
                                                        MenuItem::group("Nested 6k", vec![]),
                                                        MenuItem::group("Nested 6l", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5e",
                                                    vec![
                                                        MenuItem::group("Nested 6m", vec![]),
                                                        MenuItem::group("Nested 6n", vec![]),
                                                        MenuItem::group("Nested 6o", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5f",
                                                    vec![
                                                        MenuItem::group("Nested 6p", vec![]),
                                                        MenuItem::group("Nested 6q", vec![]),
                                                        MenuItem::group("Nested 6r", vec![]),
                                                    ],
                                                ),
                                            ],
                                        ),
                                        MenuItem::group(
                                            "Nested 4c",
                                            vec![
                                                MenuItem::group(
                                                    "Nested 5g",
                                                    vec![
                                                        MenuItem::group("Nested 6s", vec![]),
                                                        MenuItem::group("Nested 6t", vec![]),
                                                        MenuItem::group("Nested 6u", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5h",
                                                    vec![
                                                        MenuItem::group("Nested 6v", vec![]),
                                                        MenuItem::group("Nested 6w", vec![]),
                                                        MenuItem::group("Nested 6x", vec![]),
                                                    ],
                                                ),
                                                MenuItem::group(
                                                    "Nested 5i",
                                                    vec![
                                                        MenuItem::group("Nested 6y", vec![]),
                                                        MenuItem::group("Nested 6z", vec![]),
                                                        MenuItem::group("Nested 6a", vec![]),
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
```

</p>
</details> 

image

Feels like I should press down to get to the menus below, but press right...

image

Press down:
image
Press down:
image
Press right:
image
Press down:
image
Press right:
image

Aside: I'd suggest automatically adding an arrow indicating there are more items on a particular menu item.

**Comment by micielski** [comment]
> Just for reference, the way this is handled on my Mac's menu bar is that the menu that doesn't fit gets rendered the opposite direction. 

This is what I've already implemented in my PR

> The tricky part is, if it automatically rendered on left side, then which key is step in, left or right.. Neither feels right..

Maybe let's color two most outer drop-downs brighter, and make the rest darker? This way I think it would make it more obvious that the direction of keys changed

**Comment by micielski** [comment]
> image
> 
> Aside: I'd suggest automatically adding an arrow indicating there are more items on a particular menu item.

Maybe additionally to this arrow, if we were to go with this stacking we could maybe also do something about the background color so it's clearer that these aren't a one big drop-down but four

**Comment by shuoli84** [comment]
Thanks for the ideas, let me try them out. Will come back later.

**Comment by shuoli84** [comment]
I think I find a more intuitive way. No stack, no left right dance. Instead, let's shift all the menus left, ensure the right most drop down displays.

**Comment by shuoli84** [comment]
@micielski @joshka Take a look?

**Comment by shuoli84** [comment]
Added a new example
```
cargo run --example nested_group
```

**Comment by micielski** [comment]
> @micielski @joshka Take a look?

Looks good to me! Such a simple solution :D

**Comment by joshka** [comment]
Neat.
I think if you're after perfecting this, then rendering should take into account if any menus will cause wrapping:
E.g. when you have this:
image
Pressing down here should intuitively not remove the indent, it should leave a space where Nested 4 was instead. Here's what happens instead
image
And what it looks like if things are wide enough:
image

**Comment by shuoli84** [comment]
@joshka yea, I noticed it too, but didn't figure out a good and simple way to solve it.. Maybe just leave the space if any child is a group?

**Comment by joshka** [comment]
> @joshka yea, I noticed it too, but didn't figure out a good and simple way to solve it.. Maybe just leave the space if any child is a group?

👍  I think that would be a good approach

**Comment by shuoli84** [comment]
@micielski @joshka updated, take a look?

**Comment by joshka** [comment]
LGTM :)

**Review by joshka — APPROVED** [review]

**Comment by micielski** [comment]
LGTM too!

**Pull request merged**
